###############################
# SETTINGS
###############################

# FONT
font_family monospace
font_size 12.0

# Used to style underline in nvim (https://github.com/lukas-reineke/indent-blankline.nvim)
modify_font underline_position +2
modify_font underline_thickness 150%

cursor_shape underline
cursor_blink_interval -1
cursor_stop_blinking_after 15.0

url_style curly
copy_on_select no
enable_audio_bell no
allow_remote_control yes
clipboard_control write-clipboard write-primary
term xterm-kitty

###############################
# MAPPINGS
###############################
map ctrl+shift+o kitten hints --type=linenum --linenum-action=window nvr --servername /tmp/nvim.pipe --remote +{line} {path}
map ctrl+shift+g scroll_end
map ctrl+shift+l show_last_command_output

###############################
# APPEARANCE
###############################
window_padding_width 5.0

# mosel color scheme
foreground #B9B9CA
background #16161d
cursor #B9B9CA
color0 #16161d
color8 #4F4F69
color1 #EE1B1B
color9 #EE1B1B
color2 #71f4ae
color10 #71f4ae
color3 #F5DD73
color11 #F5DD73
color4 #B4E6F9
color12 #B4E6F9
color5 #d3b987
color13 #d3b987
color6 #73cef4
color14 #73cef4
color7 #B9B9CA
color15 #FFFFFF
